version: "3.8"

services:
  flatnas:
    image: qdnas/flatnas:1.0.37
    container_name: flatnas
    restart: unless-stopped
    ports:
      - "23000:3000"
    volumes:
      - ./data:/app/server/data #指定路径下新建data
      - ./music:/app/server/music #映射播放器路径
      - ./PC:/app/server/PC #映射背景路径
      - ./APP:/app/server/APP #映射移动端背景路径
      - ./doc:/app/server/doc #映射文件传输助手路径
      - /var/run/docker.sock:/var/run/docker.sock #映射Docker Socket
